/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TournamentsRouteRouteImport } from './routes/tournaments/route'
import { Route as TeamsRouteRouteImport } from './routes/teams/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TournamentsCreateRouteImport } from './routes/tournaments/create'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments/$tournamentId'
import { Route as TeamsCreateRouteImport } from './routes/teams/create'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as AuthenticatedLuckyRouteImport } from './routes/_authenticated/lucky'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardTransferRouteImport } from './routes/_authenticated/dashboard/transfer'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard/notifications'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRouteRoute = TournamentsRouteRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRouteRoute = TeamsRouteRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TournamentsRouteRoute,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsRouteRoute,
} as any)
const TournamentsCreateRoute = TournamentsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TournamentsRouteRoute,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/$tournamentId',
  path: '/$tournamentId',
  getParentRoute: () => TournamentsRouteRoute,
} as any)
const TeamsCreateRoute = TeamsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeamsRouteRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRouteRoute,
} as any)
const AuthenticatedLuckyRoute = AuthenticatedLuckyRouteImport.update({
  id: '/lucky',
  path: '/lucky',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTransferRoute =
  AuthenticatedDashboardTransferRouteImport.update({
    id: '/dashboard/transfer',
    path: '/dashboard/transfer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/dashboard/notifications',
    path: '/dashboard/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teams': typeof TeamsRouteRouteWithChildren
  '/tournaments': typeof TournamentsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/news': typeof NewsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/lucky': typeof AuthenticatedLuckyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/create': typeof TeamsCreateRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/tournaments/create': typeof TournamentsCreateRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/transfer': typeof AuthenticatedDashboardTransferRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/news': typeof NewsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/lucky': typeof AuthenticatedLuckyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/create': typeof TeamsCreateRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/tournaments/create': typeof TournamentsCreateRoute
  '/teams': typeof TeamsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/transfer': typeof AuthenticatedDashboardTransferRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/teams': typeof TeamsRouteRouteWithChildren
  '/tournaments': typeof TournamentsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/news': typeof NewsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/lucky': typeof AuthenticatedLuckyRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/teams/create': typeof TeamsCreateRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/tournaments/create': typeof TournamentsCreateRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/transfer': typeof AuthenticatedDashboardTransferRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teams'
    | '/tournaments'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/news'
    | '/reset-password'
    | '/lucky'
    | '/teams/$teamId'
    | '/teams/create'
    | '/tournaments/$tournamentId'
    | '/tournaments/create'
    | '/teams/'
    | '/tournaments/'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/transfer'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/news'
    | '/reset-password'
    | '/lucky'
    | '/teams/$teamId'
    | '/teams/create'
    | '/tournaments/$tournamentId'
    | '/tournaments/create'
    | '/teams'
    | '/tournaments'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/transfer'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/teams'
    | '/tournaments'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/news'
    | '/reset-password'
    | '/_authenticated/lucky'
    | '/teams/$teamId'
    | '/teams/create'
    | '/tournaments/$tournamentId'
    | '/tournaments/create'
    | '/teams/'
    | '/tournaments/'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/transfer'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  TeamsRouteRoute: typeof TeamsRouteRouteWithChildren
  TournamentsRouteRoute: typeof TournamentsRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NewsRoute: typeof NewsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof TournamentsRouteRoute
    }
    '/teams/': {
      id: '/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof TeamsRouteRoute
    }
    '/tournaments/create': {
      id: '/tournaments/create'
      path: '/create'
      fullPath: '/tournaments/create'
      preLoaderRoute: typeof TournamentsCreateRouteImport
      parentRoute: typeof TournamentsRouteRoute
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof TournamentsRouteRoute
    }
    '/teams/create': {
      id: '/teams/create'
      path: '/create'
      fullPath: '/teams/create'
      preLoaderRoute: typeof TeamsCreateRouteImport
      parentRoute: typeof TeamsRouteRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRouteRoute
    }
    '/_authenticated/lucky': {
      id: '/_authenticated/lucky'
      path: '/lucky'
      fullPath: '/lucky'
      preLoaderRoute: typeof AuthenticatedLuckyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/transfer': {
      id: '/_authenticated/dashboard/transfer'
      path: '/dashboard/transfer'
      fullPath: '/dashboard/transfer'
      preLoaderRoute: typeof AuthenticatedDashboardTransferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLuckyRoute: typeof AuthenticatedLuckyRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardTransferRoute: typeof AuthenticatedDashboardTransferRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLuckyRoute: AuthenticatedLuckyRoute,
  AuthenticatedDashboardNotificationsRoute:
    AuthenticatedDashboardNotificationsRoute,
  AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  AuthenticatedDashboardTransferRoute: AuthenticatedDashboardTransferRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TeamsRouteRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  TeamsCreateRoute: typeof TeamsCreateRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const TeamsRouteRouteChildren: TeamsRouteRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  TeamsCreateRoute: TeamsCreateRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}

const TeamsRouteRouteWithChildren = TeamsRouteRoute._addFileChildren(
  TeamsRouteRouteChildren,
)

interface TournamentsRouteRouteChildren {
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRoute
  TournamentsCreateRoute: typeof TournamentsCreateRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

const TournamentsRouteRouteChildren: TournamentsRouteRouteChildren = {
  TournamentsTournamentIdRoute: TournamentsTournamentIdRoute,
  TournamentsCreateRoute: TournamentsCreateRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}

const TournamentsRouteRouteWithChildren =
  TournamentsRouteRoute._addFileChildren(TournamentsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  TeamsRouteRoute: TeamsRouteRouteWithChildren,
  TournamentsRouteRoute: TournamentsRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  NewsRoute: NewsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
